openapi: 3.0.1
info:
  title: 3d model ingestion service
  description: Uploading new 3d models
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /models:
    post:
      operationId: createModel
      summary: Creates a new job and invokes a new model ingestion flow
      tags:
        - models
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payload'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '5XX':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    payload:
      type: object
      description: 3d model payload
      required:
        - modelPath
        - tilesetFilename
        - metadata
      properties:
        modelPath:
          type: string
          description: Model files location path
          example: '/home/libotadmin/NewYork'
        tilesetFilename:
          type: string
          description: Model tileset filename
          example: 'tileset.json'
        metadata:
          $ref: './Schema/3dCatalog/3dMetadata.yaml#/components/schemas/payload'
    model:
      type: object
      description: 3d model metadata for 3d model upload
      required:
        - modelPath
        - tilesetFilename
        - metadata
      properties:
        modelId:
          type: string
          format: uuid
          description: Ingestion model unique identifier
        jobId:
          type: string
          format: uuid
          description: Ingestion job unique identifier
        flowId:
          type: string
          format: uuid
          description: Ingestion flow unique identifier
        modelPath:
          type: string
          description: Model files location path
          example: '/home/libotadmin/NewYork'
        tilesetFilename:
          type: string
          description: Model tileset filename
          example: 'tileset.json'
        metadata:
          $ref: './Schema/3dCatalog/3dMetadata.yaml#/components/schemas/payload'
