openapi: 3.0.1
info:
  title: 3d model ingestion service
  description: Uploading new 3d models
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /models:
    post:
      operationId: createModel
      summary: Creates a new job and invokes a new model ingestion flow
      tags:
        - models
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payload'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '5XX':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    payload:
      type: object
      description: 3d model payload
      required:
        - modelPath
        - tilesetFilename
        - metadata
      properties:
        modelPath:
          type: string
          description: Model files location path
        tilesetFilename:
          type: string
          description: Model tileset filename
        metadata:
          $ref: '#/components/schemas/metadata'
    model:
      type: object
      description: 3d model metadata for 3d model upload
      required:
        - modelPath
        - tilesetFilename
        - metadata
      properties:
        modelId:
          type: string
          format: uuid
          description: Ingestion model unique identifier
        jobId:
          type: string
          format: uuid
          description: Ingestion job unique identifier
        flowId:
          type: string
          format: uuid
          description: Ingestion flow unique identifier
        modelPath:
          type: string
          description: Model files location path
        tilesetFilename:
          type: string
          description: Model tileset filename
        metadata:
          $ref: '#/components/schemas/metadata'
    metadata:
      type: object
      description: 3d tiles metadata payload
      properties:
        productName:
          type: string
        productVersion:
          type: string
        productType:
          type: string
        description:
          type: string
        creationDate:
          type: string
          format: date-time
          description: Creation date
        sourceDateStart:
          type: string
          format: date-time
        sourceDateEnd:
          type: string
          format: date-time
        minResolutionMeter:
          type: number
        maxResolutionMeter:
          type: number
        minResolutionDeg:
          type: number
        maxResolutionDeg:
          type: number
        nominalResolution:
          type: string
        minAccuracyCE90:
          type: number
        maxAccuracyCE90:
          type: number
        accuracyLE90:
          type: number
        accuracySE90:
          type: number
        relativeAccuracyLE90:
          type: number
        visualAccuracy:
          type: number
        sensors:
          type: string
        footprint:
          type: string
        heightRangeFrom:
          type: number
        heightRangeTo:
          type: number
        srsId:
          type: number
        srsName:
          type: string
        srsOrigin:
          type: string
        region:
          type: string
        classification:
          type: string
        compartmentalization:
          type: string
        productionSystem:
          type: string
        productionSystemVer:
          type: string
        producerName:
          type: string
        productionMethod:
          type: string
        minFlightAlt:
          type: number
        maxFlightAlt:
          type: number
        geographicArea:
          type: string
        boundingBox:
          type: string
