openapi: 3.0.1
info:
  title: 3d model ingestion service
  description: Uploading new 3d models
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8082
paths:
  /models:
    post:
      operationId: createModel
      summary: Creates a new job and invokes a new model ingestion flow
      tags:
        - models
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payload'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '5XX':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    payload:
      type: object
      description: 3d model payload
      required:
        - modelPath
        - tilesetFilename
        - metadata
      properties:
        modelPath:
          type: string
          description: Model files location path
        tilesetFilename:
          type: string
          description: Model tileset filename
        metadata:
          $ref: '#/components/schemas/metadata'
    model:
      type: object
      description: 3d model metadata for 3d model upload
      required:
        - modelPath
        - tilesetFilename
        - metadata
      properties:
        modelId:
          type: string
          format: uuid
          description: Ingestion model unique identifier
        jobId:
          type: string
          format: uuid
          description: Ingestion job unique identifier
        flowId:
          type: string
          format: uuid
          description: Ingestion flow unique identifier
        modelPath:
          type: string
          description: Model files location path
        tilesetFilename:
          type: string
          description: Model tileset filename
        metadata:
          $ref: '#/components/schemas/metadata'
    metadata:
      type: object
      description: 3d tiles metadata payload
      required:
        - identifier
        - typename
        - schema
        - mdSource
        - xml
        - anytext
        - insertDate
      properties:
        identifier:
          type: string
          description: Unique identifier
        typename:
          type: string
          description: Typename for the metadata; typically the value of the root element tag (e.g. csw:Record, gmd:MD_Metadata)
        schema:
          type: string
          description: Schema for the metadata; typically the target namespace (e.g. http://www.opengis.net/cat/csw/2.0.2, http://www.isotc211.org/2005/gmd)
        mdSource:
          type: string
          description: MD source
        xml:
          type: string
          description: Full XML representation
        anytext:
          type: string
          description: Bag of XML element text values, used for full text search
        insertDate:
          type: string
          format: date-time
          description: Date of insertion
        creationDate:
          type: string
          format: date-time
          description: Creation date
        validationDate:
          type: string
          format: date-time
          description: Validation date
        wktGeometry:
          type: string
          description: Well-Known-Text markup language for representing vector geometry objects
        title:
          type: string
          description: Title
        producerName:
          type: string
          description: The organization that produced/supplied the product
          enum:
            - IDFMU
          default: IDFMU
        description:
          type: string
          description: Description
        type:
          type: string
          description: Type
        classification:
          type: string
          description: Product classification
        srs:
          type: string
          description: The product reference system, including a vertical data
        projectName:
          type: string
          description: Project name
        version:
          type: string
          description: Version
        centroid:
          type: string
          description: Centroid
        footprint:
          type: string
          description: Footprint
        timeBegin:
          type: string
          format: date-time
          description: Begining time
        timeEnd:
          type: string
          format: date-time
          description: Ending time
        sensorType:
          type: string
          description: The sensor used as the source of the product
        region:
          type: string
          description: Region
        nominalResolution:
          type: string
          description: Nominal resolution
        accuracyLE90:
          type: string
          description: LE90 of the height values
        horizontalAccuracyCE90:
          type: string
          description: CE90 of location of elevation points
        relativeAccuracyLE90:
          type: string
          description: LE90 of distance measurement
        estimatedPrecision:
          type: string
          description: Estimated precision
        measuredPrecision:
          type: string
          description: Measured precision
