apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      volumes:
      - name: ingestion-storage
        persistentVolumeClaim:
          claimName: {{ .Values.storage.ingestionSourcePvc.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        volumeMounts: 
            - name: ingestion-storage
              mountPath: {{ .Values.storage.pv.ingestionPv.hostPath }}
        env:
        - name: SERVER_PORT
          value: {{ .Values.service.internalPort | quote }}
        - name: JOB_SERVICE_URL
          value: {{ tpl .Values.jobServiceUrl . | quote }}
        - name: FLOW_SERVICE_URL
          value: {{ tpl .Values.flowServiceUrl . | quote }}
        - name: MOUNT_PATH
          value: {{ tpl .Values.paths.mountPath . | quote }}
        - name: BASE_PATH
          value: {{ tpl .Values.paths.basePath . | quote }}    
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.service.internalPort | int }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.service.internalPort | int }}
