{{- if .Values.storage.ingestionSourcePvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.ingestionSourcePvc.name }}
  labels:
    app: {{ template "discrete-ingestion.name" . }}
    component: discrete-ingestion
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}  
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.ingestionSourcePvc.size }}
{{- end }}