
# The port on which the service should listen
port: 8080

# Name of the image tu pull from registry
image: mapcolonies/3d-model-ingestion-service:v1.3.0

replicaCount: 1

service:
  internalPort: 8080
  externalPort: 8080

jobServiceUrl: http://discrete-ingestion-db:8080/jobs
flowServiceUrl: http://nifi:8080

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ printf \"%s-%s\" .Release.Name .Chart.Name | trunc 63 | trimSuffix \"-\" }} rewrite=/"

  path: /3d-model-ingestion-service/

  hosts: ["minikube.local"]

route:
  enabled: false

  annotations:
    haproxy.router.openshift.io/rewrite-target: "/"