
ingestionService:
  # The port on which the service should listen
  port: 8080

  # Name of the image tu pull from registry
  image: mapcolonies/3d-model-ingestion-service:latest

  jobServiceUrl: http://localhost:8081/jobs
  flowServiceUrl: http://localhost:8082/flows

ingress:
  enabled: true

route:
  enabled: false