global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

image: acrarolibotnonprod.azurecr.io/3d-model-ingestion-service:v1-rc-profile

enabled: true
environment: development
initialDelaySeconds: 60
# nodePort: 30030
replicaCount: 1

cloudProvider:
  dockerRegistryUrl: 'acrarolibotnonprod.azurecr.io'
  flavor: openshift

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

# # external
# dbConfig:
#   host: 10.8.1.15
#   username: postgres
#   password: postgres
#   database: pycsw-3d-dev
#   sslAuth:
#     enabled: false
#     secretName: secret-name
#     certFileName: postgresql.crt
#     keyFileName: postgresql.key
#     caFileName: root.crt

ingress:
  enabled: false

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ printf \"%s-%s\" .Release.Name .Chart.Name | trunc 63 | trimSuffix \"-\" }} rewrite=/"

    path: /3d-model-ingestion-service/

route:
  enabled: true

  annotations:
    haproxy.router.openshift.io/rewrite-target: "/"